[package]
name = "crossoutld12"
description = "Crossout DirectX 12 patcher for Linux"
version = "1.1.1"
author = "varsity"
edition = "2021"

[profile.release]
incremental = true
codegen-units = 1
panic = "abort"
opt-level = 3
strip = true
lto = "fat"
